# Main Page Setup

title: Jan Leuca Espelien's Portfolio

# Hero Section
name: Jan Espelien
headline: EE @ Columbia | Draper Labs
description: >-
  Rising sophomore at Columbia University majoring in electrical engineering with a minor in operations research. Incoming analog and power electronics intern at Draper, passionate about hands-on prototyping, PCB design, and 3D modeling.

profile_image: ./assets/images/profile-image/avatar.jpeg

# Link your resume
resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing

# Set up external links - this will show up as small icons next to your name.
external-links:
  linkedin: jan-espelien    # https://www.linkedin.com/in/jan-espelien
  github: 
  stackoverflow:
  medium:
  x-twitter:
  threads:
  instragram:
  youtube:
  discord:
  bluesky:

# Skills Section - Add the list of your Skills by categories/tools.
skills:
  - category: Technical
    tools:
      - Altium
      - Fusion 360 (Autodesk)
      - SPICE
      - Simulink
      - Inventor (Autodesk)
  - category: Software & PCB Design
    tools:
      - Eagle
      - KiCad
      - LTSpice
      - Inventor
      - Altium
      - Fusion
      - Simulink
  - category: Programming Languages
    tools:
      - Python
      - Java
      - C++
      - C
      - R
  - category: PCB Design
    tools:
      - Altium Designer
      - Eagle
      - KiCad

# Contact Form Setup
formspree-key: 

# Active theme (Updatethis to switch themes). Make sure to keep the indentation the same.
colors:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"

lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"

pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"

#########################################################################################################

# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
